# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.runs/synth_1/Top_final_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param synth.incrementalSynthesisCache C:/Users/kccistc/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-7032-DESKTOP-7CFQ9ND/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.cache/wt [current_project]
set_property parent.project_path D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/new/baudrate.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/UART_STOPWATCH/UART_STOPWATCH.srcs/sources_1/imports/UCH_Vivado_Work/0515_stopwatch/0515_stopwatch.srcs/sources_1/new/btn_debounce.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/new/command_to_btn.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/DHT11_UCH/DHT11_UCH.srcs/sources_1/new/dht_11.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/sources_1/imports/UCH_Vivado_Work/2025_0527_fifo/2025_0527_fifo.srcs/sources_1/new/fifo.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/new/fnd_controller_top.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/UART_STOPWATCH/UART_STOPWATCH.srcs/sources_1/imports/UCH_Vivado_Work/0515_stopwatch/0515_stopwatch.srcs/sources_1/new/realwatch_cu.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/UART_STOPWATCH/UART_STOPWATCH.srcs/sources_1/imports/UCH_Vivado_Work/0515_stopwatch/0515_stopwatch.srcs/sources_1/new/realwatch_dp.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/sources_1/new/sender_uart.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/SR04_Ultrasonic/SR04_Ultrasonic.srcs/sources_1/new/sr04_controller.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/new/stop_uart_controller.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/UART_STOPWATCH/UART_STOPWATCH.srcs/sources_1/imports/UCH_Vivado_Work/0515_stopwatch/0515_stopwatch.srcs/sources_1/new/stopwatch_cu.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/UCH_Vivado_Work/UART_STOPWATCH/UART_STOPWATCH.srcs/sources_1/imports/UCH_Vivado_Work/0515_stopwatch/0515_stopwatch.srcs/sources_1/new/stopwatch_dp.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/new/uart_controller.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/new/uart_rx.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/imports/new/uart_tx.v
  D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/sources_1/new/Top_final_module.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/constrs_1/imports/UCH_Vivado_Work/Basys-3-Master.xdc
set_property used_in_implementation false [get_files D:/UCH_Vivado_Work/Final_project_team2_test/Final_project_team2.srcs/constrs_1/imports/UCH_Vivado_Work/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_final_module -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_final_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_final_module_utilization_synth.rpt -pb Top_final_module_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
